### ISSUE TITLE
Are there ways to work with directories?

### ISSUE THREAD

**Issue by nackjicholson** [scottwernervt/cloudstorage#13]
I'm looking for a solution that treats cloud storage systems and local similarly as a filesystem. If I open a Container may I list subdirectories or blobs in that directory? Are there ways to open directory paths as Containers?

Cheers,

Will

**Comment by scottwernervt** [comment]
> If I open a Container may I list subdirectories or blobs in that directory?

You can only list the blobs in the container. A quick test on AWS S3 shows a subdirectory as a blob. I can look into supporting subdirectories so they behave like containers.

```python
>>> from cloudstorage.drivers.amazon import S3Driver
>>> storage = S3Driver(key='', secret='')
>>> for container in storage:
>>>    for blob in container:
>>>        print(container, blob)
<Container cloudstorage-test S3> <Blob new-folder/ cloudstorage-test S3>
<Container cloudstorage-test S3> <Blob new-folder/tux-aerospace-trans-128x128.ico cloudstorage-test S3>
<Container cloudstorage-test S3> <Blob tux-aerospace-trans-250x250.png cloudstorage-test S3>
```

> Are there ways to open directory paths as Containers?

Yes, set the container's parent directory as the key for the local storage driver.

```python
from cloudstorage.drivers.local import LocalDriver

# /mnt/cloudstorage/storage_a/container
storage_a = LocalDriver(key='/mnt/cloudstorage/storage_a')
# /mnt/cloudstorage/storage_b/container
storage_b = LocalDriver(key='/mnt/cloudstorage/storage_b')
```

**Comment by nackjicholson** [comment]
Thanks for the examples!
