### ISSUE TITLE
Open source cloud storage [enhancement]

### ISSUE THREAD

**Issue by minusreality** [scottwernervt/cloudstorage#25]
Are there any plans to add support for an open source cloud file storage system such as [minio](https://github.com/minio/minio)

**Comment by scottwernervt** [comment]
I will look into implementing it over the weekend.

https://docs.minio.io/docs/python-client-api-reference

**Comment by scottwernervt** [comment]
Initial Minio client driver implemented. Let me know if it is missing any features.
