### ISSUE TITLE
LocalDriver not usable without manually installing xattr and filelock

### ISSUE THREAD

**Issue by jminardi** [scottwernervt/cloudstorage#41]
I installed cloudstorage and cloudstorage[local] with pip. In my python file I have:

`from cloudstorage.drivers.local import LocalDriver`

This first fails with:

`ModuleNotFoundError: No module named 'filelock'`

After manually installing filelock with pip I get:

`ModuleNotFoundError: No module named 'xattr'`

After installing xattr then the import works as expected.

**Comment by scottwernervt** [comment]
@jminardi I cannot repeat your issue:

```bash
$ pip install cloudstorage
$ pip install cloudstorage[local]
$ source test-local-driver/bin/activate
$ python
>>> from cloudstorage.drivers.local import LocalDriver
>>> storage = LocalDriver(key='/home/scwerner/downloads')
>>> list(storage)
[<Container fun LOCAL>]
```
https://cloudstorage.readthedocs.io/en/latest/#installation

**Comment by jminardi** [comment]
I just tested with a fresh docker container with only cloud storage and was not able to reproduce my original issue so the problem must come from somewhere else in the environment.

Thanks for looking into this.
