### ISSUE TITLE
Azure get_blob raises TypeError when Content MD5 missing in remote

### ISSUE THREAD

**Issue by matt-carr** [scottwernervt/cloudstorage#47]
If a blob was uploaded without content MD5, _convert_azure_blob still attempts to decode and calculate from the None value, raising a TypeError.

**Comment by scottwernervt** [comment]
This weekend I will:
- Review your PRs (thanks!)
- Get tests passing by updating packages
- Make a new release

**Comment by matt-carr** [comment]
sounds awesome, thanks for the quick turnaround!

**Comment by matt-carr** [comment]
Any updates on that ETA?

**Comment by scottwernervt** [comment]
@matt-carr Just released https://pypi.org/project/cloudstorage/0.10.0/. Thanks for the bug fixes!

**Comment by matt-carr** [comment]
Happy to help, thanks for the release!
