### ISSUE TITLE
Any chance of a new release?

### ISSUE THREAD

**Issue by matt-carr** [scottwernervt/cloudstorage#57]
Couple of new issues merged since the last release, but unfortunately still can't get them from pypi

**Comment by scottwernervt** [comment]
Yes been tied up with work but hopefully this weekend I can cut a release. Need to get the tests working again due to outdated packages like azure.

**Comment by matt-carr** [comment]
That'd be wicked, thanks :D

**Comment by scottwernervt** [comment]
New [release v0.10.1](https://github.com/scottwernervt/cloudstorage/blob/master/CHANGELOG.rst#0101-2020-04-20) which freezes azure package version until I have some time to refactor it with the latest version.
